name: Java CI with Maven

on:
  push:
    branches: [ "service" ]
  pull_request:
    branches: [ "service" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -X
